<?php
// $Id: sxjmevent.module $
/**
 * Implementation of hook_perm().
 */
function sxjmevent_perm() {
  return array(
    '管理数学建模活动',
  );
}


/**
 * Implementation of hook_menu().
 */
function sxjmevent_menu() {
  $items = array();
  $items['sxjm/event'] = array (
    'type' => MENU_NORMAL_ITEM,
    'title' => '活动管理',
    'description' => '配置数学建模相关设置',
    'page callback' => 'sxjmevent_admin',
    'page arguments' => '',
    'access callback' => 'sxjmusers_access',
    'access arguments' => array('管理数学建模活动'),
    'weight' => 6,
  );
  return $items;
}


function sxjmevent_admin() {
  return '';
}
